# This is a basic workflow to help you get started with MATLAB Actions

name: MATLAB Build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        release: [R2020b, latest]

    # The type of runner that the job will run on
    runs-on: ${{matrix.platform}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache MATLAB
        id: cache-matlab
        uses: actions/cache@v3
        with:
          path: ${{ runner.tool_cache }}/MATLAB
          key: ${{ matrix.platform }}-${{ matrix.release }}

      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2-beta
        with:
          release: ${{matrix.release}}
          products: |
            Statistics_and_Machine_Learning_Toolbox
            Simulink
            Simulink_Test
            Simulink_Check

      # Runs a set of commands using the runners shell
      - name: Check MATLAB Install
        uses: matlab-actions/run-command@v1
        with:
          command: ver

      # Runs a set of commands using the runners shell
      - name: Run all tests
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: src
          use-parallel: true
